export enum Authority {
  TEACHER = 'TEACHER',
  EXPERT = 'EXPERT',
  INTERVIEWER = 'INTERVIEWER',
  NETWORK_LEAD = 'NETWORK_LEAD',
  ITA_COORDINATOR = 'ITA_COORDINATOR',
  ITA_ADMIN = 'ITA_ADMIN',
  RECRUITER = 'RECRUITER',
  SOFTSERVE_PM = 'SOFTSERVE_PM'
}
